...

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -445,8 +445,10 @@ xcmd(){
             local p
             for p in "$@"; do
                 if ! p=$(___xcmd_which_one "$p"); then
-                    printf "%s\n" "Fail to find path for $p"
+                    printf "%s\n" "Fail to find path for $p" >&2
                     return
+                else
+                    printf "%s\n" "$p"
                 fi
             done
             ;;
